name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and run tests
      run: |
        cd client
        npm install
        npm install --save-dev @babel/plugin-proposal-private-property-in-object --legacy-peer-deps
        npm test | grep -q "Press \`a\` to run all tests" && echo "a" | npm test

    - name: Exit with success status code
      run: exit 0  # Exit with success status code



  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Change directory to server
      run: cd server

    - name: Install server dependencies
      run: npm install

    - name: Run server tests
      run: npm test
