on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests
        run: |
          cd client
          npm install --ignore-scripts
          npm test

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install bcrypt module
        run: |
          cd server
          npm install node-gyp -g
          npm install bcrypt -g
          npm install bcrypt --save

      - name: Install remaining dependencies and run tests
        run: |
          cd server
          npm install --ignore-scripts
          npx mocha backend.test.js
          env:
            MONGO_URL: ${{ secrets.MONGO_URL }}
